image: tetraweb/php

cache:
  paths:
  - vendor/

before_script:
  - docker-php-ext-enable intl
  - docker-php-ext-enable mbstring
  - docker-php-ext-enable zip
  - docker-php-ext-enable pdo_mysql
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar clear-cache
  - php -d memory_limit=-1 composer.phar install

services:
  - mysql

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

after_failure:
  script:
    - cat var/logs/test.log
  when: on_failure

php-5.6:
  image: tetraweb/php
  script:
    - php bin/console doctrine:database:create --no-interaction --if-not-exists
    - php bin/console doctrine:migrations:migrate --no-interaction
    - vendor/bin/phpcs --standard=PSR2 src/
    - vendor/bin/phpunit --colors --coverage-text
